name: Persist Tokens
on:
  workflow_run:
    workflows: ["刷步数"]
    types:
      - completed
  workflow_dispatch:

jobs:
  persist:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          current=`TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S'
          git commit -m "[${current}] persist tokens"
          git push origin master