name: 刷步数

on:
  schedule:
    - cron: '08 2 * * *'
    - cron: '22 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y

      - name: 初始化Python
 # 获取当前时间对应的最大和最小步数
 def get_min_max_by_time(hour=None, minute=None):
    if hour is None:
         hour = time_bj.hour
     if minute is None:
        minute = time_bj.minute
     time_rate = min((hour * 60 + minute) / (22 * 60), 1)
    min_step = get_int_value_default(config, 'MIN_STEP', 18000)
    max_step = get_int_value_default(config, 'MAX_STEP', 25000)
    return int(time_rate * min_step), int(time_rate * max_step)
          python3 main.py

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          git commit -m "persist tokens trigger by ${{ github.event_name }}" || true
          git push origin master || true
